image: dcr.danawa.io/alpine-k8s-java:8

variables:
  spring:
    profiles:
      active: production

stages:
  - test

cache:
  paths:
    - .m2/repository


test:
  stage: test
  script:
    - echo ${spring.profiles.active}
    - env
    - ls -al /root/
    - ls -al
    - ls -al /home/
    - sh mvnw package
    - ls -al /root/
    - ls -al
    - ls -al /home/
