image: dcr.danawa.io/alpine-k8s

stages:
  - test

cache:
  paths:
    - .m2/repository


test:
  stage: test
  script:
    - env
    - ls -al /root/
    - ls -al
    - ls -al /home/
    - sh mvnw package
    - env
    - ls -al /root/
    - ls -al
    - ls -al /home/
