image: dcr.danawa.io/alpine-k8s-java:8

stages:
  - build
  - deploy

cache:
  paths:
    - .m2/repository

before_script:
  - export IMAGE="${REGISTRY}/${CI_PROJECT_TITLE}:latest"
  - echo "${IMAGE}"

build:
  stage: build
  script:
    - sh mvnw package
    - docker build -t ${IMAGE} .
    - docker push ${IMAGE}

deploy:
  stage: deploy
  script:
    - env