image: dcr.danawa.io/alpine-k8s-java:8

stages:
  - build
  - deploy

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - /root/.m2/

before_script:
  - export IMAGE="${REGISTRY}/${CI_PROJECT_TITLE}:latest"
  - echo "${IMAGE}"

build:
  stage: build
  cache:
    key: ${CI_COMMIT_REF_SLUG}
  script:
    - ls -al 
    - ls -al /root/
    - sh mvnw package -DskipTests
    - ls -al /root/.m2
    - ls -al 
    # - docker build -t ${IMAGE} .
    # - docker push ${IMAGE}

deploy:
  stage: deploy
  cache: {}
  script:
    - kubectl patch deployment fastcatx-server -n fastcatx -p "{\"spec\":{\"template\":{\"metadata\":{\"labels\":{\"date\":\"`date +'%s'`\"}},\"spec\":{\"containers\":[{\"name\":\"fastcatx-server\",\"image\":\"${IMAGE}\"}]}}}}"
    - sleep 5
    - kubectl get pod -n fastcatx -o wide
