spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:file:~\fastcatx-server\fileDB
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    generate-ddl: true
logging:
  level:
    level:
      root: info
    com:
      danawa:
        fastcatx: debug
  file:
    path: C:\\windows\\temp\\fastcatx-server
    name: C:\\windows\\temp\\fastcatx-server\\system.log
    max-history: 7
    clean-history-on-start: true
    max-size: 100MB
fastcatx:
  admin:
    username: admin
    password: admin
    email: admin@example.com
  dictionary:
    setting: .fastcatx_dict_setting
    index: .fastcatx_dictionary
  reference:
    index: .fastcatx_reference
  build:
    name: @project.name@
    version: @project.version@