logging:
  level:
    level:
      root: info
    com:
      danawa:
        fastcatx: debug

elasticsearch:
  thread: 50
  username: fastcatx
  password: fastcatx
  nodes:
    - host: es1.danawa.io
      port: 80
      scheme: http



fastcatx:
  dictionary:
    setting: .fastcatx_dict_setting
    index: .fastcatx_dictionary
  reference:
    index: .fastcatx_reference
