logging:
  level:
    level:
      root: info
    com:
      danawa:
        fastcatx: debug

elasticsearch:
  nodes:
    - "http://es.danawa.io"
    - "http://es.danawa.io"
    - "http://es.danawa.io"



