spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:file:~\fastcatx-server\fileDB
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
logging:
  level:
    level:
      root: info
    com:
      danawa:
        fastcatx: debug
  file:
    path: C:\\windows\\temp\\fastcatx-server
    name: C:\\windows\\temp\\fastcatx-server\\system.log
    max-history: 7
    clean-history-on-start: true
    max-size: 100MB
fastcatx:
  admin:
    username: admin
    password: admin
    email: admin@example.com
  dictionary:
    setting: .fastcatx_dict_setting
#    index: .fastcatx_dict
    index: .fastcatx_dictionary
  reference:
    index: .fastcatx_reference
  collection:
    index: .fastcatx_collection
    index-suffix-a: -a
    index-suffix-b: -b
  jdbc:
    setting: .fastcatx_jdbc
  build:
    name: @project.name@
    version: @project.version@

