spring:
  h2:
    console:
      enabled: false
  datasource:
    url: jdbc:h2:file:~/fileDB
    driver-class-name: org.h2.Driver
    username: admin
    password: admin
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
logging:
  level:
    level:
      root: info
    com:
      danawa:
        fastcatx: info
  file:
    path: /var/log/fastcatx-server
    name: /var/log/fastcatx-server/application.log
    max-history: 30
    max-size: 500MB
fastcatx:
  admin:
    username: admin
    password: admin
    email: admin@example.com
  dictionary:
    setting: .fastcatx_dict_setting
    index: .fastcatx_dictionary
  reference:
    index: .fastcatx_reference
  collection:
    index: .fastcatx_collection
    index-suffix-a: -a
    index-suffix-b: -b
  build:
    name: @project.name@
    version: @project.version@